# Generated by Django 6.0.1 on 2026-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('humedad_media_global', models.FloatField(verbose_name='Humedad Media Diaria (%)')),
                ('temperatura_promedio_global', models.FloatField(verbose_name='Temperatura Media Diaria (°C)')),
                ('bateria_v', models.FloatField(verbose_name='Voltaje Medio Batería (V)')),
                ('panel_solar_v', models.FloatField(verbose_name='Voltaje Medio Panel (V)')),
                ('alerta_sequedad_relativa', models.IntegerField(default=0)),
                ('alerta_subida_brusca', models.IntegerField(default=0)),
                ('alerta_caida_brusca', models.IntegerField(default=0)),
                ('alerta_bateria_baja', models.IntegerField(default=0)),
                ('alerta_panel_bajo', models.IntegerField(default=0)),
                ('alerta_hueco_temporal', models.IntegerField(default=0)),
                ('predic_humedad_futura', models.FloatField(verbose_name='Predicción Humedad Mañana (%)')),
                ('predic_sequedad_relativa', models.IntegerField(default=0)),
                ('predic_bateria_baja', models.IntegerField(default=0)),
                ('predic_panel_bajo', models.IntegerField(default=0)),
                ('predic_hueco_temporal', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Registros diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(unique=True, verbose_name='Fecha y Hora')),
                ('humedad_media_global', models.FloatField(verbose_name='Humedad Media Global (%)')),
                ('temperatura_promedio_global', models.FloatField(verbose_name='Temperatura Promedio Global (°C)')),
                ('bateria_v', models.FloatField(verbose_name='Voltaje Batería (V)')),
                ('panel_solar_v', models.FloatField(verbose_name='Voltaje Panel Solar (V)')),
                ('alerta_sequedad_relativa', models.IntegerField(default=0, verbose_name='Alerta Sequedad')),
                ('alerta_subida_brusca', models.IntegerField(default=0, verbose_name='Alerta Subida Brusca')),
                ('alerta_caida_brusca', models.IntegerField(default=0, verbose_name='Alerta Caída Brusca')),
                ('alerta_bateria_baja', models.IntegerField(default=0, verbose_name='Alerta Batería Baja')),
                ('alerta_panel_bajo', models.IntegerField(default=0, verbose_name='Alerta Panel Bajo')),
                ('alerta_hueco_temporal', models.IntegerField(default=0, verbose_name='Alerta Hueco Temporal')),
                ('predic_humedad_futura', models.FloatField(verbose_name='Predicción Humedad Futura (%)')),
                ('predic_sequedad_relativa', models.IntegerField(default=0, verbose_name='Predicción Sequedad')),
                ('predic_bateria_baja', models.IntegerField(default=0, verbose_name='Predicción Batería Baja')),
                ('predic_panel_bajo', models.IntegerField(default=0, verbose_name='Predicción Panel Bajo')),
                ('predic_hueco_temporal', models.IntegerField(default=0, verbose_name='Predicción Hueco Temporal')),
            ],
            options={
                'verbose_name': 'Registros horarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
